theme: jekyll-theme-minimal 
title: Bioinformatics
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fcreazilla.com%2Fnodes%2F3155320-leaf-clipart&psig=AOvVaw22XB1ZBYPnKt5xbiEourDp&ust=1679074486561000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCMiK5YP-4P0CFQAAAAAdAAAAABAE
